# Generated by Django 4.2.30 on 2026-05-18 03:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('python3', 'Python 3')], default='python3', max_length=20)),
                ('code', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', '等待判题'), ('JUDGING', '正在判题'), ('ACCEPTED', '答案正确'), ('WRONG_ANSWER', '答案错误'), ('TIME_LIMIT_EXCEEDED', '运行超时'), ('RUNTIME_ERROR', '运行错误'), ('SYSTEM_ERROR', '系统错误')], default='PENDING', max_length=30)),
                ('score', models.PositiveIntegerField(default=0)),
                ('time_used', models.PositiveIntegerField(default=0, help_text='单位：ms')),
                ('memory_used', models.PositiveIntegerField(default=0, help_text='单位：KB，初版可为空')),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('judged_at', models.DateTimeField(blank=True, null=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='problems.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='JudgeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', '等待判题'), ('JUDGING', '正在判题'), ('ACCEPTED', '答案正确'), ('WRONG_ANSWER', '答案错误'), ('TIME_LIMIT_EXCEEDED', '运行超时'), ('RUNTIME_ERROR', '运行错误'), ('SYSTEM_ERROR', '系统错误')], max_length=30)),
                ('time_used', models.PositiveIntegerField(default=0)),
                ('output', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='submissions.submission')),
                ('testcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_results', to='problems.testcase')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
