# Generated by Django 4.2.30 on 2026-05-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='judgeresult',
            name='memory_used',
            field=models.PositiveIntegerField(default=0, help_text='单位：KB'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='memory_used',
            field=models.PositiveIntegerField(default=0, help_text='单位：KB'),
        ),
    ]
